### PR TITLE
Fixes callback typing in credentials refresh

### LINKED ISSUE #3140: [typescript] 'Credentials' interface for 'refresh(err)' is not properly modelled for no error
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
While providing a refresh callback to the AWS Credential implementation, the typings in the callback expect explicitly the existence of a non-null `AWSError` object as argument of the callback. However, both the underlying [JS code](https://github.com/aws/aws-sdk-js/blob/804b8500b9169fa65f3d9941957b6f773c364994/lib/credentials.js#L195) and [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Credentials.html#refresh-property) suggest that the defined error needs to be passed to the callback only if the refresh failed.

The [current typings mandate the callback signature to accept a defined `AWSError`](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials.d.ts#L41) which is not required for happy cases of refresh. Thus, the signature needs to be corrected.

**To Reproduce (observed behavior)**
This code below would throw TS typings error:
```typescript
import * as AWS from `aws-sdk`;

class MyCredentials extends AWS.Credentials {
  // Implement the refresh method
  function refresh(callback: (err: AWS.AWSError) => void) {
    //                           ^ this is the function signature in typings
    try {
      // Some refresh mechanism: myRefresh();
      // Call back with no error as per docs, but typings don't allow
      callback();
    } catch (e) {
      // This call is legit
      callback(e);
    }
  }
}
```

**Expected behavior**
The expected behaviour is to be able to call back with the AWS callback hook with no error in case of successful refresh. This is possible in JS but not in TS due to the interface definition.

**Additional context**
I am gladly willing to raise a PR with the required typings fix and documentation. :)

### PR DESCRIPTION
**Pull request by anmoldalmia**
Fixes #3140 by adding optional qualifier in typings to allow the `refresh()` callback in `Credentials` interface to be called without a defined `AWSError` object. This condition holds true in the event of a successful refresh of credentials where no error is generated. Propagated the change in all extensions of the `Credentials` interface.

##### Checklist

- [x] `npm run test` passes
- [x] `.d.ts` file is updated
- [x] changelog is added, `npm run add-change`

### CODE REVIEW

File: ts/credentials.ts [hunk 1]
```diff
@@ -15,7 +15,7 @@ creds.getPromise().then(
 );
 
 if (creds.needsRefresh()) {
-    creds.refresh(err => {
+    creds.refresh((err = undefined) => {
```
Comment (AllanFly120) [inline ts/credentials.ts]: Looks like defaul value [was added in Node6](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters), since the library still needs to be run on older node versions(>= 0.10), we cannot use this synctax for now.

Comment (anmoldalmia) [reply ts/credentials.ts:18]: This is the typescript typing. Wouldn't TSC take care of the target node version transpilation under this constraint? I am assuming those settings to be available in tsconfig as we are already supporting older versions.

Comment (anmoldalmia) [reply ts/credentials.ts:18]: @AllanFly120 does the above address/satisfy your concern? The reckon this is a simple PR and would be nice to act on it sooner. :)
