### PR TITLE
Normalizes Metadata keys when calling s3.getSignedUrl when using sigv4

### LINKED ISSUE #1013: When using sigV4, s3.getSignedUrl does not normalize Metadata keys properly
This seems very similar or perhaps the same as issue #747. When creating a signed URL for upload to S3 while using SigV4, if you have mixed-case metadata then the signature does not match. I assume this is because the data being signed is mixed-case while the generated query-params are lower-cased. Perhaps this was not fixed when #747 was fixed because SigV4 uses a different code path. Or maybe just a regression?

The following test demonstrates the issue:
```javascript
var AWS = require('aws-sdk');
var http = require('http');
var request = require('request');

console.log('AWS SDK version', AWS.VERSION);

var s3v4 = new AWS.S3({
	signatureVersion: 'v4',
	region: "us-west-1"
});

var s3default = new AWS.S3({
	region: "us-west-1"
});

// set bucket here
var myBucket = 'my-bucket';

function paramsWithMetadata(md) {
	return {
		Bucket: myBucket,
		Key: `users/foo/bar.txt`,
		ContentType: 'text/plain',
		Metadata: md
	}
}

function doUploadWithMetadata(testId, md, s3) {
	var params = paramsWithMetadata(md);
	s3.getSignedUrl('putObject', params, function (err, url) {
		if (err) {
			console.error(err);
			return;
		}
		request.put({
			url: url,
			body: 'foobar',
			headers: {
				'Content-Length': 6,
				Origin: 'http://localhost:3000',
				'content-type': 'text/plain',
				Accept: '*/*',
				Referer: 'http://localhost:3000/debug/test',
				'Accept-Encoding': 'gzip, deflate, sdch, br'
			}
		}, function (err, result, body) {
			console.log('\n\n\n--------------------------------------');
			console.log(testId);
			console.log('--------------------------------------');
			if (err) {
				console.error(err);
				return;
			}
			console.log(result.statusCode, result.statusMessage);
			console.log(body);
		});
	});
}

doUploadWithMetadata('v4: all lowercase metadata test returns 200 OK', {
	'myfunkymetadataoooo': 'some meta data'
}, s3v4);
doUploadWithMetadata('v4: mixed case metadata test returns 403 forbidden', {
		'myFunkyMetaDataOoOo': 'some meta data'
}, s3v4);
doUploadWithMetadata('default: all lowercase metadata test returns 200 OK', {
	'myfunkymetadataoooo': 'some meta data'
}, s3default);
doUploadWithMetadata('default: mixed case metadata test returns 200 OK', {
		'myFunkyMetaDataOoOo': 'some meta data'
}, s3default);

```
output:
```
$ node s3KmsMetadataTest.js 
AWS SDK version 2.3.17

--------------------------------------
v4: mixed case metadata test returns 403 forbidden
--------------------------------------
403 'Forbidden'
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>

... clipped ...

</Error>

--------------------------------------
default: all lowercase metadata test returns 200 OK
--------------------------------------
200 'OK'

--------------------------------------
v4: all lowercase metadata test returns 200 OK
--------------------------------------
200 'OK'

--------------------------------------
default: mixed case metadata test returns 200 OK
--------------------------------------
200 'OK'
```

### PR DESCRIPTION
**Pull request by chrisradek**
Fixes #1013 
/cc @LiuJoyceC

### CODE REVIEW

File: lib/signers/presign.js [hunk 1]
```diff
@@ -51,6 +51,8 @@ function signedUrlSigner(request) {
   AWS.util.each(request.httpRequest.headers, function (key, value) {
     if (key === expiresHeader) key = 'Expires';
     if (key.indexOf('x-amz-meta-') === 0) {
```
Comment (LiuJoyceC) [inline lib/signers/presign.js]: `if (key.toLowerCase().indexOf('x-amz-meta-') === 0)` in case the `'x-amz-meta-'` part isn't lowercased?

**Comment by LiuJoyceC** [comment]
🚢
